// <auto-generated />
using System;
using FresiaFlow.Adapters.Outbound.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FresiaFlow.Adapters.Outbound.Persistence.Migrations
{
    [DbContext(typeof(FresiaFlowDbContext))]
    [Migration("20251226130509_AddInvoiceProcessingSnapshots")]
    partial class AddInvoiceProcessingSnapshots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FresiaFlow.Domain.Banking.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExternalAccountId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("BankAccounts");
                });

            modelBuilder.Entity("FresiaFlow.Domain.Banking.BankTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ExternalTransactionId")
                        .HasColumnType("text");

                    b.Property<bool>("IsReconciled")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ReconciledWithInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reference")
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId");

                    b.HasIndex("ExternalTransactionId");

                    b.ToTable("BankTransactions");
                });

            modelBuilder.Entity("FresiaFlow.Domain.Invoices.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReconciledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReconciledWithTransactionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("FresiaFlow.Domain.Invoices.IssuedInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ClientTaxId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasDefaultValue("ES");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SourceFilePath")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Series", "InvoiceNumber")
                        .IsUnique();

                    b.ToTable("IssuedInvoices");
                });

            modelBuilder.Entity("FresiaFlow.Domain.InvoicesReceived.InvoiceProcessingSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClassificationCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ClassificationConfidence")
                        .HasColumnType("numeric");

                    b.Property<string>("ClassificationJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentLanguage")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("ExtractionCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ExtractionConfidence")
                        .HasColumnType("numeric");

                    b.Property<string>("ExtractionHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ExtractionJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("ExtractionVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("FallbackCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FallbackReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("FallbackTriggered")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("OcrCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("OcrConfidence")
                        .HasColumnType("numeric");

                    b.Property<string>("OcrLayoutJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("OcrText")
                        .HasColumnType("text");

                    b.Property<string>("SourceFileHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SourceFilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SupplierCandidate")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValidationCompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ValidationErrors")
                        .HasColumnType("text");

                    b.Property<int>("ValidationStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceFileHash")
                        .IsUnique();

                    b.HasIndex("SourceFilePath");

                    b.ToTable("InvoiceProcessingSnapshots", (string)null);
                });

            modelBuilder.Entity("FresiaFlow.Domain.InvoicesReceived.InvoiceReceived", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<decimal?>("ExtractionConfidence")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("IrpfRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("OriginalFilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProcessedFilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SupplierAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("SupplierTaxId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("TaxRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber");

                    b.ToTable("InvoicesReceived", (string)null);
                });

            modelBuilder.Entity("FresiaFlow.Domain.InvoicesReceived.InvoiceReceivedLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("InvoiceReceivedId")
                        .HasColumnType("uuid");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<decimal?>("TaxRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceReceivedId", "LineNumber");

                    b.ToTable("InvoiceReceivedLines", (string)null);
                });

            modelBuilder.Entity("FresiaFlow.Domain.InvoicesReceived.InvoiceReceivedPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BankTransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvoiceReceivedId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BankTransactionId");

                    b.HasIndex("InvoiceReceivedId");

                    b.HasIndex("PaymentDate");

                    b.ToTable("InvoiceReceivedPayments", (string)null);
                });

            modelBuilder.Entity("FresiaFlow.Domain.Reconciliation.ReconciliationCandidate", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MatchScore")
                        .HasColumnType("numeric");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InvoiceId", "TransactionId");

                    b.ToTable("ReconciliationCandidates");
                });

            modelBuilder.Entity("FresiaFlow.Domain.Sync.InvoiceSourceConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<int>("TotalFilesSynced")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SourceType", "Name");

                    b.ToTable("InvoiceSourceConfigs");
                });

            modelBuilder.Entity("FresiaFlow.Domain.Sync.OneDriveSyncConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ClientSecret")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DriveId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("FolderPath")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSyncError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("SyncIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("TenantId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TotalFilesSynced")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("OneDriveSyncConfigs");
                });

            modelBuilder.Entity("FresiaFlow.Domain.Sync.SyncedFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ExternalModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileHash");

                    b.HasIndex("Source", "ExternalId")
                        .IsUnique();

                    b.ToTable("SyncedFiles");
                });

            modelBuilder.Entity("FresiaFlow.Domain.Tasks.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPinned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RelatedInvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("RelatedTransactionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("IsCompleted", "IsPinned", "Priority");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("FresiaFlow.Domain.Banking.BankTransaction", b =>
                {
                    b.HasOne("FresiaFlow.Domain.Banking.BankAccount", null)
                        .WithMany("Transactions")
                        .HasForeignKey("BankAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FresiaFlow.Domain.Shared.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("BankTransactionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Amount");

                            b1.HasKey("BankTransactionId");

                            b1.ToTable("BankTransactions");

                            b1.WithOwner()
                                .HasForeignKey("BankTransactionId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("FresiaFlow.Domain.Invoices.Invoice", b =>
                {
                    b.OwnsOne("FresiaFlow.Domain.Shared.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Amount");

                            b1.HasKey("InvoiceId");

                            b1.ToTable("Invoices");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("FresiaFlow.Domain.Invoices.IssuedInvoice", b =>
                {
                    b.OwnsOne("FresiaFlow.Domain.Shared.Money", "TaxAmount", b1 =>
                        {
                            b1.Property<Guid>("IssuedInvoiceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("TaxAmountCurrency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("TaxAmount");

                            b1.HasKey("IssuedInvoiceId");

                            b1.ToTable("IssuedInvoices");

                            b1.WithOwner()
                                .HasForeignKey("IssuedInvoiceId");
                        });

                    b.OwnsOne("FresiaFlow.Domain.Shared.Money", "TaxableBase", b1 =>
                        {
                            b1.Property<Guid>("IssuedInvoiceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("TaxableBaseCurrency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("TaxableBase");

                            b1.HasKey("IssuedInvoiceId");

                            b1.ToTable("IssuedInvoices");

                            b1.WithOwner()
                                .HasForeignKey("IssuedInvoiceId");
                        });

                    b.OwnsOne("FresiaFlow.Domain.Shared.Money", "TotalAmount", b1 =>
                        {
                            b1.Property<Guid>("IssuedInvoiceId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("TotalAmountCurrency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("TotalAmount");

                            b1.HasKey("IssuedInvoiceId");

                            b1.ToTable("IssuedInvoices");

                            b1.WithOwner()
                                .HasForeignKey("IssuedInvoiceId");
                        });

                    b.Navigation("TaxAmount")
                        .IsRequired();

                    b.Navigation("TaxableBase")
                        .IsRequired();

                    b.Navigation("TotalAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("FresiaFlow.Domain.InvoicesReceived.InvoiceReceived", b =>
                {
                    b.OwnsOne("FresiaFlow.Domain.Shared.Money", "IrpfAmount", b1 =>
                        {
                            b1.Property<Guid>("InvoiceReceivedId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("IrpfCurrency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("IrpfAmount");

                            b1.HasKey("InvoiceReceivedId");

                            b1.ToTable("InvoicesReceived");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceReceivedId");
                        });

                    b.OwnsOne("FresiaFlow.Domain.Shared.Money", "SubtotalAmount", b1 =>
                        {
                            b1.Property<Guid>("InvoiceReceivedId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("SubtotalCurrency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("SubtotalAmount");

                            b1.HasKey("InvoiceReceivedId");

                            b1.ToTable("InvoicesReceived");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceReceivedId");
                        });

                    b.OwnsOne("FresiaFlow.Domain.Shared.Money", "TaxAmount", b1 =>
                        {
                            b1.Property<Guid>("InvoiceReceivedId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("TaxCurrency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("TaxAmount");

                            b1.HasKey("InvoiceReceivedId");

                            b1.ToTable("InvoicesReceived");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceReceivedId");
                        });

                    b.OwnsOne("FresiaFlow.Domain.Shared.Money", "TotalAmount", b1 =>
                        {
                            b1.Property<Guid>("InvoiceReceivedId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("TotalCurrency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("TotalAmount");

                            b1.HasKey("InvoiceReceivedId");

                            b1.ToTable("InvoicesReceived");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceReceivedId");
                        });

                    b.Navigation("IrpfAmount");

                    b.Navigation("SubtotalAmount")
                        .IsRequired();

                    b.Navigation("TaxAmount");

                    b.Navigation("TotalAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("FresiaFlow.Domain.InvoicesReceived.InvoiceReceivedLine", b =>
                {
                    b.HasOne("FresiaFlow.Domain.InvoicesReceived.InvoiceReceived", "InvoiceReceived")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceReceivedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FresiaFlow.Domain.Shared.Money", "LineTotal", b1 =>
                        {
                            b1.Property<Guid>("InvoiceReceivedLineId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("LineTotalCurrency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("LineTotal");

                            b1.HasKey("InvoiceReceivedLineId");

                            b1.ToTable("InvoiceReceivedLines");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceReceivedLineId");
                        });

                    b.OwnsOne("FresiaFlow.Domain.Shared.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<Guid>("InvoiceReceivedLineId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("UnitPriceCurrency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 4)
                                .HasColumnType("numeric(18,4)")
                                .HasColumnName("UnitPrice");

                            b1.HasKey("InvoiceReceivedLineId");

                            b1.ToTable("InvoiceReceivedLines");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceReceivedLineId");
                        });

                    b.Navigation("InvoiceReceived");

                    b.Navigation("LineTotal")
                        .IsRequired();

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("FresiaFlow.Domain.InvoicesReceived.InvoiceReceivedPayment", b =>
                {
                    b.HasOne("FresiaFlow.Domain.InvoicesReceived.InvoiceReceived", "InvoiceReceived")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceReceivedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("FresiaFlow.Domain.Shared.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("InvoiceReceivedPaymentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("Currency");

                            b1.Property<decimal>("Value")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("Amount");

                            b1.HasKey("InvoiceReceivedPaymentId");

                            b1.ToTable("InvoiceReceivedPayments");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceReceivedPaymentId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("InvoiceReceived");
                });

            modelBuilder.Entity("FresiaFlow.Domain.Banking.BankAccount", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("FresiaFlow.Domain.InvoicesReceived.InvoiceReceived", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
